
package org.soaeasy.ws.oagis.itemmaster._10;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OAGIS_ItemMaster_v10", targetNamespace = "http://www.soaeasy.org/ws/oagis/itemmaster/10", wsdlLocation = "META-INF/oagis/10/contract/ItemMaster.wsdl")
public class OAGISItemMasterV10
    extends Service
{

    private final static URL OAGISITEMMASTERV10_WSDL_LOCATION;
    private final static WebServiceException OAGISITEMMASTERV10_EXCEPTION;
    private final static QName OAGISITEMMASTERV10_QNAME = new QName("http://www.soaeasy.org/ws/oagis/itemmaster/10", "OAGIS_ItemMaster_v10");

    static {
        OAGISITEMMASTERV10_WSDL_LOCATION = org.soaeasy.ws.oagis.itemmaster._10.OAGISItemMasterV10 .class.getClassLoader().getResource("META-INF/oagis/10/contract/ItemMaster.wsdl");
        WebServiceException e = null;
        if (OAGISITEMMASTERV10_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/oagis/10/contract/ItemMaster.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        OAGISITEMMASTERV10_EXCEPTION = e;
    }

    public OAGISItemMasterV10() {
        super(__getWsdlLocation(), OAGISITEMMASTERV10_QNAME);
    }

    public OAGISItemMasterV10(WebServiceFeature... features) {
        super(__getWsdlLocation(), OAGISITEMMASTERV10_QNAME, features);
    }

    public OAGISItemMasterV10(URL wsdlLocation) {
        super(wsdlLocation, OAGISITEMMASTERV10_QNAME);
    }

    public OAGISItemMasterV10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OAGISITEMMASTERV10_QNAME, features);
    }

    public OAGISItemMasterV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAGISItemMasterV10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemMasterPortType
     */
    @WebEndpoint(name = "ItemMasterPort")
    public ItemMasterPortType getItemMasterPort() {
        return super.getPort(new QName("http://www.soaeasy.org/ws/oagis/itemmaster/10", "ItemMasterPort"), ItemMasterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemMasterPortType
     */
    @WebEndpoint(name = "ItemMasterPort")
    public ItemMasterPortType getItemMasterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.soaeasy.org/ws/oagis/itemmaster/10", "ItemMasterPort"), ItemMasterPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OAGISITEMMASTERV10_EXCEPTION!= null) {
            throw OAGISITEMMASTERV10_EXCEPTION;
        }
        return OAGISITEMMASTERV10_WSDL_LOCATION;
    }

}
