package org.soaeasy.ws.oagis.itemmaster._10;

import javax.annotation.security.RolesAllowed;
import javax.ejb.Stateless;
import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.openapplications.oagis._10.GetItemMasterType;
import org.openapplications.oagis._10.ShowItemMasterType;
import org.openapplications.oagis._10.SyncItemMasterType;
import org.openapplications.oagis._10.SyncResponseItemMasterType;

// JBoss Specific Annotations
import org.jboss.ws.api.annotation.WebContext;
import org.jboss.ejb3.annotation.SecurityDomain;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated
 * source version: 2.2
 * 
 */
@WebService(
    portName = "ItemMasterPort", 
    serviceName = "OAGIS_ItemMaster_v10", 
    targetNamespace = "http://www.soaeasy.org/ws/oagis/itemmaster/10", 
    wsdlLocation = "META-INF/oagis/10/contract/ItemMaster.wsdl", 
    endpointInterface = "org.soaeasy.ws.oagis.itemmaster._10.ItemMasterPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@Stateless
@RolesAllowed("AUTHORISED")
@SecurityDomain("cxfservice-security-domain")
@WebContext(contextRoot="/ws/oagis/itemmaster", urlPattern="/*", authMethod="BASIC", transportGuarantee="NONE", secureWSDLAccess=false)
public class OAGIS_ItemMaster_v10_ItemMasterPortImpl implements
    ItemMasterPortType {

  public OAGIS_ItemMaster_v10_ItemMasterPortImpl() {
  }

  /**
   * 
   * @param syncItemMaster
   * @return returns org.openapplications.oagis._10.SyncResponseItemMasterType
   */
  public SyncResponseItemMasterType syncItemMaster(
      final SyncItemMasterType syncItemMaster) {
    final Object object = syncItemMaster.getAny();
    final SyncResponseItemMasterType ret = new SyncResponseItemMasterType();
    ret.setAny(object);
    return ret;
  }

  /**
   * 
   * @param getItemMaster
   * @return returns org.openapplications.oagis._10.ShowItemMasterType
   */
  public ShowItemMasterType getItemMaster(final GetItemMasterType getItemMaster) {
    final Object object = getItemMaster.getAny();
    final ShowItemMasterType ret = new ShowItemMasterType();
    ret.setAny(object);
    return ret;
  }
}